/**
 * Photo source for /photography.
 *
 * The Pexels Collection identified by $PEXELS_COLLECTION_ID is the single
 * source of truth. Drop a photo into that collection on pexels.com → it
 * appears on the site on the next ISR revalidation (hourly) or the next
 * build. No images live in this repo.
 *
 * Hand-edited captions live in public/data/photo-overrides.json, keyed by
 * the Pexels photo id (as a string). Anything you put there wins over the
 * auto-generated Pexels `alt`. Schema:
 *
 *   { "12345678": { "location": "Salinas Grandes, Jujuy",
 *                   "description": "Optional better alt text" } }
 *
 * Failure modes & fallbacks:
 *   - PEXELS_* env vars missing  → use the committed snapshot
 *   - Pexels API throws / 5xx    → use the committed snapshot, log warning
 *   - Collection returns empty   → keep the snapshot (a wiped collection is
 *                                  almost certainly an outage or a misconfig,
 *                                  not what we want users to see)
 *
 * The snapshot at public/data/photos.json is regenerated by
 * `pnpm sync-photos` and as part of `prebuild`, so deploys ship a fresh
 * fallback.
 */

import photosSnapshot from "../../public/data/photos.json";
import photoOverrides from "../../public/data/photo-overrides.json";

export interface Photo {
  id: number;
  pexels_url: string;
  image_url: string;
  description: string;
  width: number;
  height: number;
  /** Hand-curated caption from photo-overrides.json. */
  location?: string;
}

export interface PhotoOverride {
  location?: string;
  description?: string;
}

interface PexelsMedia {
  type: "Photo" | "Video";
  id: number;
  width: number;
  height: number;
  url: string;
  alt?: string;
  src: {
    original: string;
    large2x: string;
    large: string;
    medium: string;
    [k: string]: string;
  };
}

interface PexelsCollectionResponse {
  media: PexelsMedia[];
  total_results: number;
  page: number;
  per_page: number;
  next_page?: string;
}

const OVERRIDES = photoOverrides as Record<string, PhotoOverride>;

const PER_PAGE = 80;
const REVALIDATE_SECONDS = 60 * 60; // 1h

/** Cap on Pexels API pages we'll walk. Defensive — a runaway loop here
 * burns the API quota and slows page loads. 25 * 80 = 2000 photos, well
 * beyond any realistic portfolio. */
const MAX_PAGES = 25;

/** Per-request timeout. Pexels' p99 is well under 5s; 10s is forgiving. */
const FETCH_TIMEOUT_MS = 10_000;

interface FetchOptions {
  /** Next.js ISR revalidation hint. Ignored outside Next runtime. */
  revalidate?: number;
}

/**
 * Walks every page of a Pexels Collection and returns the photos in the
 * order the API returns them (most-recently-added first by default).
 *
 * Throws on HTTP error or network failure — callers decide whether to
 * fall back. No retries: at the per-hour cadence we run this, a transient
 * failure is fine to surface and we'll try again next revalidation.
 */
export async function fetchPexelsCollection(
  collectionId: string,
  apiKey: string,
  opts: FetchOptions = {},
): Promise<Photo[]> {
  const out: Photo[] = [];
  for (let page = 1; page <= MAX_PAGES; page++) {
    const url =
      `https://api.pexels.com/v1/collections/${encodeURIComponent(collectionId)}` +
      `?per_page=${PER_PAGE}&page=${page}&type=photos`;

    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), FETCH_TIMEOUT_MS);
    let json: PexelsCollectionResponse;
    try {
      const res = await fetch(url, {
        headers: { Authorization: apiKey },
        signal: controller.signal,
        // `next.revalidate` is a Next.js extension — silently ignored by
        // plain Node fetch in the snapshot script, used by the RSC.
        ...(opts.revalidate !== undefined && {
          next: { revalidate: opts.revalidate },
        }),
      });
      if (!res.ok) {
        throw new Error(
          `Pexels collection ${collectionId}: HTTP ${res.status} ${res.statusText}`,
        );
      }
      json = (await res.json()) as PexelsCollectionResponse;
    } finally {
      clearTimeout(timer);
    }

    for (const m of json.media) {
      if (m.type !== "Photo") continue;
      out.push({
        id: m.id,
        pexels_url: m.url,
        image_url: m.src.large2x,
        description: m.alt ?? "",
        width: m.width,
        height: m.height,
      });
    }
    if (!json.next_page || json.media.length < PER_PAGE) break;
  }
  return out;
}

/**
 * Merge `photo-overrides.json` on top of a photo list. Mutates a copy;
 * input is left intact. Missing keys = pass-through.
 */
export function applyOverrides(photos: Photo[]): Photo[] {
  return photos.map((p) => {
    const o = OVERRIDES[String(p.id)];
    if (!o) return p;
    return {
      ...p,
      // Override description only if a non-empty string is provided so we
      // don't accidentally erase Pexels' alt by leaving "" in the override.
      description: o.description?.trim() ? o.description : p.description,
      ...(o.location?.trim() ? { location: o.location } : {}),
    };
  });
}

/**
 * Read the committed snapshot. Used as fallback and at build time when
 * env isn't wired up. Already trusted (we wrote it ourselves).
 */
export function getSnapshotPhotos(): Photo[] {
  return photosSnapshot;
}

/**
 * Live photos for the gallery. Prefers a Pexels Collection fetch; falls
 * back to the snapshot on any failure so the page never goes blank.
 */
export async function getPhotos(): Promise<Photo[]> {
  const id = process.env.PEXELS_COLLECTION_ID;
  const key = process.env.PEXELS_API_KEY;

  if (id && key) {
    try {
      const live = await fetchPexelsCollection(id, key, {
        revalidate: REVALIDATE_SECONDS,
      });
      if (live.length > 0) return applyOverrides(live);
      console.warn(
        "[photos] Pexels collection returned 0 photos — using snapshot",
      );
    } catch (e) {
      console.error(
        "[photos] live fetch failed, using snapshot:",
        e instanceof Error ? e.message : e,
      );
    }
  }
  return applyOverrides(getSnapshotPhotos());
}
