/**
 * Enrich the resources catalog by re-deriving title, description, category,
 * countries, cities, topics, and quality FROM SCRATCH for each saved link.
 *
 * Inputs to Claude are intentionally limited to the URL + the page content
 * fetched from it. The legacy title/description/category in resources.ts are
 * NOT shown to the model — the old data was generated by a weaker LLM and
 * shouldn't poison the new pass.
 *
 * Run via Claude Code's local CLI (`claude -p`), so token cost is billed
 * against the user's Claude.ai subscription / usage credits, not a separate
 * API key.
 *
 * Two on-disk caches make the run resumable:
 *   - scripts/.cache/resource-pages.json       — fetched page content per URL
 *   - scripts/.cache/resource-enrichment.json  — Claude responses per URL
 *
 * Re-running picks up where it left off. To iterate on the prompt without
 * re-fetching pages, delete only the enrichment cache.
 *
 * CLI:
 *   npx tsx scripts/enrich-resources.ts                      # all uncached
 *   npx tsx scripts/enrich-resources.ts --limit=20           # test run
 *   npx tsx scripts/enrich-resources.ts --concurrency=4
 *   npx tsx scripts/enrich-resources.ts --reset-enrichment   # re-enrich all
 *   npx tsx scripts/enrich-resources.ts --dry-run            # no Claude calls
 *
 * Output: public/data/resources/resources-enriched.json (committed)
 */

import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { createHash } from "node:crypto";
import { readFile, writeFile, mkdir, unlink } from "node:fs/promises";
import { existsSync } from "node:fs";
import { join } from "node:path";
import { resources as RESOURCES_BY_TAB } from "../src/app/metadata/resources";

const exec = promisify(execFile);

// ── Paths ──────────────────────────────────────────────────────────────

const CACHE_DIR = "scripts/.cache";
const PAGE_CACHE = join(CACHE_DIR, "resource-pages.json");
const ENRICH_CACHE = join(CACHE_DIR, "resource-enrichment.json");
const OUT_DIR = "public/data/resources";
const OUT_FILE = join(OUT_DIR, "resources-enriched.json");

// ── Types ──────────────────────────────────────────────────────────────

interface PageContent {
  title?: string;
  metaDescription?: string;
  ogTitle?: string;
  ogDescription?: string;
  bodyText: string;
  fetchedAt: string;
  // Set when the fetch returned HTTP 200 + HTML but the content is unusable
  // (Cloudflare/DataDome challenge, empty SPA shell, etc.). Prompt builder
  // treats this the same as a fetch failure and asks Claude to classify
  // from the URL alone.
  degradationReason?: string;
}

type FetchFailureReason =
  | "network"
  | "timeout"
  | "http-4xx"
  | "http-5xx"
  | "non-html"
  | "empty";

interface PageFailure {
  url: string;
  error: string;
  reason: FetchFailureReason;
  attemptedAt: string;
}

type FetchResult =
  | { ok: true; page: PageContent }
  | {
      ok: false;
      reason: FetchFailureReason;
      message: string;
      httpStatus?: number;
    };

interface EnrichedFields {
  title: string;
  description: string;
  category: string;
  countries: string[];
  cities: string[];
  topics: string[];
  quality: "high" | "medium" | "low";
  confidence: "high" | "medium" | "low";
}

interface EnrichedResource extends EnrichedFields {
  id: string;
  url: string;
  enrichedAt: string;
}

interface EnrichmentFailure {
  url: string;
  error: string;
  rawResponse?: string;
  attemptedAt: string;
}

// ── CLI parsing ────────────────────────────────────────────────────────

interface CliOpts {
  limit?: number;
  concurrency: number;
  resetPages: boolean;
  resetEnrichment: boolean;
  dryRun: boolean;
  onlyUrls?: Set<string>;
  onlyUrlsFile?: string;
}

function parseArgs(argv: string[]): CliOpts {
  const opts: CliOpts = {
    concurrency: 8,
    resetPages: false,
    resetEnrichment: false,
    dryRun: false,
  };
  for (const arg of argv) {
    if (arg.startsWith("--limit=")) opts.limit = Number(arg.slice(8));
    else if (arg.startsWith("--concurrency="))
      opts.concurrency = Number(arg.slice(14));
    else if (arg === "--reset-pages") opts.resetPages = true;
    else if (arg === "--reset-enrichment") opts.resetEnrichment = true;
    else if (arg === "--dry-run") opts.dryRun = true;
    else if (arg.startsWith("--only=")) {
      opts.onlyUrls = new Set(
        arg
          .slice(7)
          .split(",")
          .map((s) => s.trim())
          .filter(Boolean),
      );
    } else if (arg.startsWith("--only-file=")) {
      opts.onlyUrlsFile = arg.slice(12);
    }
  }
  return opts;
}

// ── URL → stable id ────────────────────────────────────────────────────

function urlId(url: string): string {
  return createHash("sha1").update(url).digest("hex").slice(0, 12);
}

// ── Collect input URLs ─────────────────────────────────────────────────

function collectUrls(): string[] {
  const seen = new Set<string>();
  for (const items of Object.values(RESOURCES_BY_TAB)) {
    for (const r of items as Array<{ url?: string }>) {
      if (r.url && !seen.has(r.url)) seen.add(r.url);
    }
  }
  return [...seen];
}

// ── Page fetching ──────────────────────────────────────────────────────

// Realistic browser UA — some sites block default fetch UAs (Cloudflare, etc.).
const UA =
  "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36";

// Mimic a real browser as much as a plain `fetch` can. Doesn't defeat real
// WAFs but clears the shallow UA/Accept/Lang checks a lot of sites do.
const FETCH_HEADERS = {
  "User-Agent": UA,
  Accept:
    "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
  "Accept-Language": "en-US,en;q=0.9",
};

const FETCH_TIMEOUT_MS = 15_000;
const BODY_CHAR_LIMIT = 3000;
const FETCH_ATTEMPTS = 2;

function extractMatch(html: string, regex: RegExp): string | undefined {
  const m = html.match(regex);
  return m?.[1]?.trim();
}

function extractPageContent(html: string): PageContent {
  const title = extractMatch(html, /<title[^>]*>([^<]+)<\/title>/i);
  const metaDescription = extractMatch(
    html,
    /<meta[^>]+name=["']description["'][^>]+content=["']([^"']+)["']/i,
  );
  const ogTitle = extractMatch(
    html,
    /<meta[^>]+property=["']og:title["'][^>]+content=["']([^"']+)["']/i,
  );
  const ogDescription = extractMatch(
    html,
    /<meta[^>]+property=["']og:description["'][^>]+content=["']([^"']+)["']/i,
  );
  // Strip scripts/styles, then tags, then collapse whitespace.
  const bodyText = html
    .replace(/<script[^>]*>[\s\S]*?<\/script>/gi, "")
    .replace(/<style[^>]*>[\s\S]*?<\/style>/gi, "")
    .replace(/<noscript[^>]*>[\s\S]*?<\/noscript>/gi, "")
    .replace(/<[^>]+>/g, " ")
    .replace(/&nbsp;/g, " ")
    .replace(/\s+/g, " ")
    .trim()
    .slice(0, BODY_CHAR_LIMIT);
  return {
    title,
    metaDescription,
    ogTitle,
    ogDescription,
    bodyText,
    fetchedAt: new Date().toISOString(),
  };
}

// Cloudflare / DataDome / Sucuri / generic anti-bot interstitials return
// HTTP 200 with HTML that doesn't describe the actual resource. Feeding that
// HTML to Claude makes it think the page is about "Just a moment...", so we
// strip the content and fall back to URL-only classification.
function detectBotWall(html: string, title: string | undefined): string | null {
  const lower = html.toLowerCase();
  const t = (title ?? "").toLowerCase().trim();
  if (t.includes("just a moment")) return "Cloudflare challenge";
  if (t.startsWith("attention required") && lower.includes("cloudflare"))
    return "Cloudflare block page";
  if (t.includes("checking your browser")) return "browser-verification page";
  if (t.includes("please verify you are a human"))
    return "human-verification page";
  if (t.startsWith("access denied")) return "access-denied page";
  if (lower.includes("cf-browser-verification")) return "Cloudflare challenge";
  if (lower.includes("cf_chl_opt") || lower.includes("__cf_chl"))
    return "Cloudflare challenge";
  if (lower.includes("ddos protection by cloudflare"))
    return "Cloudflare DDoS-protect page";
  if (lower.includes("enable javascript and cookies to continue"))
    return "JS-required bot wall";
  if (lower.includes("/datadome-") || lower.includes("datado.me"))
    return "DataDome challenge";
  if (lower.includes("perimeterx") && lower.includes("blocked"))
    return "PerimeterX block";
  return null;
}

// JS-only SPAs return an empty <body> shell. Without a headless browser we
// can't see the real content, so flag it instead of feeding the model
// bundle markup.
function detectEmptyShell(html: string, bodyText: string): string | null {
  if (bodyText.length >= 200) return null;
  const scriptCount = (html.match(/<script\b/gi) ?? []).length;
  if (scriptCount >= 2 && html.length > 5_000) {
    return `JS-only shell (${scriptCount} scripts, ${bodyText.length}-char body)`;
  }
  return null;
}

function classifyError(e: unknown): {
  reason: FetchFailureReason;
  message: string;
} {
  if (!(e instanceof Error)) return { reason: "network", message: String(e) };
  // undici wraps the real error in `e.cause` — TypeError: fetch failed has the
  // actual SocketError / DNSError underneath. Peek through one layer.
  const cause = (e as Error & { cause?: unknown }).cause;
  const causeErr = cause instanceof Error ? cause : undefined;
  const code =
    (e as NodeJS.ErrnoException).code ??
    (causeErr as NodeJS.ErrnoException | undefined)?.code;
  const msg = e.message ?? "";
  const causeMsg = causeErr?.message ?? "";

  if (
    e.name === "TimeoutError" ||
    e.name === "AbortError" ||
    causeErr?.name === "TimeoutError" ||
    causeErr?.name === "AbortError" ||
    code === "UND_ERR_HEADERS_TIMEOUT" ||
    code === "UND_ERR_BODY_TIMEOUT" ||
    code === "UND_ERR_CONNECT_TIMEOUT" ||
    msg.includes("aborted") ||
    msg.includes("timeout")
  ) {
    return { reason: "timeout", message: "request timed out" };
  }
  if (code === "ENOTFOUND" || code === "EAI_AGAIN")
    return { reason: "network", message: `DNS lookup failed (${code})` };
  if (code === "ECONNREFUSED")
    return { reason: "network", message: "connection refused" };
  if (code === "ECONNRESET" || code === "UND_ERR_SOCKET")
    return { reason: "network", message: causeMsg || "connection reset" };
  if (code) return { reason: "network", message: `${code}: ${causeMsg || msg}` };
  return { reason: "network", message: causeMsg || msg || "unknown network error" };
}

async function fetchPageOnce(url: string): Promise<FetchResult> {
  let res: Response;
  try {
    res = await fetch(url, {
      headers: FETCH_HEADERS,
      signal: AbortSignal.timeout(FETCH_TIMEOUT_MS),
      redirect: "follow",
    });
  } catch (e) {
    const c = classifyError(e);
    return { ok: false, reason: c.reason, message: c.message };
  }

  if (!res.ok) {
    return {
      ok: false,
      reason: res.status >= 500 ? "http-5xx" : "http-4xx",
      message: `HTTP ${res.status} ${res.statusText}`.trim(),
      httpStatus: res.status,
    };
  }

  const ct = (res.headers.get("content-type") ?? "").toLowerCase();
  if (
    ct &&
    !ct.includes("html") &&
    !ct.includes("xml") &&
    !ct.includes("text/plain")
  ) {
    return { ok: false, reason: "non-html", message: `content-type ${ct}` };
  }

  let html: string;
  try {
    html = await res.text();
  } catch (e) {
    const c = classifyError(e);
    return {
      ok: false,
      reason: c.reason,
      message: `body read failed: ${c.message}`,
    };
  }

  if (!html.trim()) {
    return { ok: false, reason: "empty", message: "empty response body" };
  }

  const page = extractPageContent(html);
  const botWall = detectBotWall(html, page.title);
  if (botWall) {
    return {
      ok: true,
      page: {
        bodyText: "",
        fetchedAt: new Date().toISOString(),
        degradationReason: botWall,
      },
    };
  }
  const emptyShell = detectEmptyShell(html, page.bodyText);
  if (emptyShell) {
    return {
      ok: true,
      page: {
        bodyText: "",
        fetchedAt: new Date().toISOString(),
        degradationReason: emptyShell,
      },
    };
  }
  return { ok: true, page };
}

// Retry once on transient errors (timeout, network, 5xx, 429). 4xx and
// degraded-content results are permanent — no point in re-hitting them.
async function fetchWithRetry(url: string): Promise<FetchResult> {
  let last: FetchResult | null = null;
  for (let attempt = 1; attempt <= FETCH_ATTEMPTS; attempt++) {
    const result = await fetchPageOnce(url);
    if (result.ok) return result;
    last = result;
    const retryable =
      result.reason === "timeout" ||
      result.reason === "network" ||
      result.reason === "http-5xx" ||
      (result.reason === "http-4xx" && result.httpStatus === 429);
    if (!retryable) return result;
    if (attempt < FETCH_ATTEMPTS) {
      const delayMs = result.httpStatus === 429 ? 5_000 : 2_000 * attempt;
      await new Promise((r) => setTimeout(r, delayMs));
    }
  }
  return last!;
}

// ── Claude prompt ──────────────────────────────────────────────────────

const PROMPT_TEMPLATE = `Enrich a saved web resource for a personal knowledge index. Re-derive everything FROM SCRATCH using only the URL and page content below — ignore anything you might guess about prior categorization.

URL: {{URL}}

Page <title>: {{TITLE}}
Page meta description: {{META_DESC}}
OG title: {{OG_TITLE}}
OG description: {{OG_DESC}}

Page content (extracted, first ~3000 chars):
{{BODY}}

Return ONE JSON object matching this schema. No fences, no preamble, no commentary:

{
  "title": string,
  "description": string,
  "category": string,
  "countries": string[],
  "cities": string[],
  "topics": string[],
  "quality": "high" | "medium" | "low",
  "confidence": "high" | "medium" | "low"
}

## VOICE

Direct, declarative, slightly wry. A smart friend telling you what something is — not a corporate landing page, not a Wikipedia editor, not an SEO blurb. Sentence fragments are fine. Active voice, present tense. Specific over generic.

NEVER write: "Useful for", "Useful as", "A great resource", "A curated list of", "Comprehensive guide", "Allows users to", "Helps you", "Enables you to", "Likely", "appears to be", "seems to be". If a sentence wants to start with one of these, rewrite it.

## DESCRIPTION (1–2 sentences, 15–35 words)

First beat: what it is. Second beat: a fact that grounds or surprises — the angle, the author, the era, the niche. Don't tack on "why you'd care" framing; the facts already do that work. Be declarative even when content is thin — uncertainty belongs in the confidence field, not in hedging prose.

GOOD: "Tavis Ormandy ports Lotus 1-2-3 natively to Linux thirty years late, recovering the lost LPL SDK from BBS warez tapes along the way. One of the great reverse-engineering writeups."
GOOD: "The canonical index of services you can self-host. If you're trying to ditch a SaaS, the open-source replacement is probably in here."
GOOD: "Wikipedia on the formal pan-Arab register (fusha) used in writing, media, and education. Background for the gap between MSA and the spoken dialects."
GOOD: "Tradle from the Observatory of Economic Complexity — guess the country from its export profile. Wordle mechanics on top of UN trade data."

BAD: "Curated list of free, open-source network services and web applications you can run on your own servers. Canonical reference for anyone building a self-hosted stack."
   (corporate listicle voice; "useful as / canonical reference for" tic)
BAD: "Likely a CTF or bug bounty post from skii.dev."
   (hedging in prose — push the uncertainty into the confidence field and state it plainly)
BAD: "A great resource for developers looking to learn..."
   (marketing voice)

## TITLE (3–8 words)

The resource's actual name. Strip SEO suffixes ("— Wikipedia", "| GitHub"), publication names, and marketing taglines. Then judge: would someone outside the niche know what this thing is from the bare name alone? If no, you MUST append a brief em-dash clarifier. If yes, leave it bare.

GOOD bare names (self-explanatory): "Modern Standard Arabic", "Awesome Self-Hosted", "Project Based Learning"
GOOD with clarifier (opaque without it): "tweakcn — shadcn/ui theme editor", "ranlab — random self-hosted-app picker", "Tradle — trade-guessing game", "Darling — macOS-on-Linux translation layer"
BAD: "tweakcn" alone, "ranlab" alone, "Darling" alone (all opaque; reader has no idea what these are)

## CATEGORY (pick the SHARPEST single fit)

- coding — about writing code: tutorials, language references, libraries, framework docs, algorithms, code archeology, reverse-engineering writeups
- technology — software/hardware you use or encounter: tools, apps, FOSS lists, infra, hardware, product security research. The catchall for "tech things that aren't specifically about authoring code"
- wikipedia — anything on wikipedia.org or similar wiki-style reference sites (host wins over subject)
- youtube — youtube.com channels and videos (host wins)
- podcasts — podcast feeds or shows
- articles — long-form essays/blog posts that don't fit a stronger category. Culture, politics, ideas, philosophy, narrative non-fiction. Default catchall for prose.
- languages — learning or studying human languages
- games — games to play (browser/web games included)
- travel — trip reports, destination guides, transit/visa/logistics
- history — historical events, eras, biographies, archives
- geography — physical/political geography, maps, atlases
- business — entrepreneurship, finance, careers, economics, personal money management
- health — fitness, nutrition, medicine, mental health
- random — genuinely quirky / "I just liked this" with no stronger fit

Decision rule: if a tech writeup is on Wikipedia → wikipedia (host wins). A reverse-engineering blog post on someone's personal site → coding. A YouTube video about Argentina → youtube. A news article about tech → articles (not technology).

## COUNTRIES / CITIES

Set when the resource is anchored to a place — its culture, history, economy, language, food, travel, news. URL hints count (".ar" TLD, "/argentina/" in the path, city name in the slug). DO NOT include a country just because the author lives there, or because it's mentioned once in passing.

When a city is set, always include its parent country.

Examples:
- Guide to Argentina's blue dollar economy → countries: ["argentina"], cities: []
- Buenos Aires walking-tour site → countries: ["argentina"], cities: ["buenos-aires"]
- Wikipedia on Modern Standard Arabic → countries: [] (pan-Arab, not anchored)
- Generic inflation article that happens to cite Argentina → countries: []

Use lowercase hyphenated slugs: "argentina", "united-states", "united-kingdom", "buenos-aires", "washington-dc", "sao-paulo".

## TOPICS (3–6 tags)

Specific over generic: "blue-dollar" not "money", "asado" not "food", "limera1n" not "exploit", "f-sharp" not "functional-programming-language". Don't stack near-synonyms ("curated-list" + "awesome-list" + "github-list" — pick one). Lowercase, hyphenated.

## QUALITY (be stingy)

- high — deep, evergreen, authoritative, the canonical thing in its niche, or unusually insightful original work. ~25% of resources, not 70%.
- medium — solid and useful but findable elsewhere. A fine guide, a reasonable intro, a competent listicle. Most things land here.
- low — shallow, dated, redundant with better resources, or marginal. "Why did I save this" territory.

If you're marking everything "high" you're being too generous. Calibrate against the rest of the open web.

## CONFIDENCE

- high — you read real page content and what the resource is was clear
- medium — partial info but enough to feel solid
- low — URL-only inference, bot wall, JS shell, paywall

If the page content is missing, paywalled, a JS-only shell, or a bot-check page, infer from the URL alone (host + path are usually enough — "github.com/x/y", "en.wikipedia.org/wiki/Asado") and set confidence "low". Still phrase the description declaratively — no "likely" or "appears to".

Return ONLY the JSON object.`;

function buildPrompt(
  url: string,
  page: PageContent | null,
  fetchFailure?: { reason: FetchFailureReason; message: string },
): string {
  const noContentMsg = page?.degradationReason
    ? `(no usable content — ${page.degradationReason}; classify from URL alone)`
    : fetchFailure
      ? `(could not fetch page content — ${fetchFailure.reason}: ${fetchFailure.message}; classify from URL alone)`
      : "(could not fetch page content; classify from URL alone)";
  const useFields = page && !page.degradationReason;
  return PROMPT_TEMPLATE.replace("{{URL}}", url)
    .replace("{{TITLE}}", useFields ? (page.title ?? "(not available)") : noContentMsg)
    .replace(
      "{{META_DESC}}",
      useFields ? (page.metaDescription ?? "(not available)") : noContentMsg,
    )
    .replace(
      "{{OG_TITLE}}",
      useFields ? (page.ogTitle ?? "(not available)") : noContentMsg,
    )
    .replace(
      "{{OG_DESC}}",
      useFields ? (page.ogDescription ?? "(not available)") : noContentMsg,
    )
    .replace("{{BODY}}", useFields ? page.bodyText : noContentMsg);
}

// ── Claude CLI invocation ──────────────────────────────────────────────

interface ClaudeJsonEnvelope {
  type: string;
  is_error: boolean;
  result: string;
  total_cost_usd?: number;
  usage?: { input_tokens?: number; output_tokens?: number };
}

const CLAUDE_TIMEOUT_MS = 120_000;

async function callClaude(prompt: string): Promise<ClaudeJsonEnvelope> {
  const { stdout } = await exec(
    "claude",
    ["-p", prompt, "--output-format=json"],
    { timeout: CLAUDE_TIMEOUT_MS, maxBuffer: 4 * 1024 * 1024 },
  );
  return JSON.parse(stdout) as ClaudeJsonEnvelope;
}

function stripFences(s: string): string {
  return s
    .replace(/^```(?:json)?\s*/i, "")
    .replace(/\s*```\s*$/i, "")
    .trim();
}

function parseEnrichment(text: string): EnrichedFields {
  const parsed = JSON.parse(stripFences(text)) as Partial<EnrichedFields>;
  // Light schema sanity-check — fail fast if Claude returned something weird.
  const required: (keyof EnrichedFields)[] = [
    "title",
    "description",
    "category",
    "countries",
    "cities",
    "topics",
    "quality",
    "confidence",
  ];
  for (const k of required) {
    if (parsed[k] === undefined) throw new Error(`missing field: ${k}`);
  }
  return parsed as EnrichedFields;
}

// ── Concurrency primitive ──────────────────────────────────────────────

async function runWithConcurrency<T, R>(
  items: T[],
  concurrency: number,
  worker: (item: T, index: number) => Promise<R>,
): Promise<R[]> {
  const results: R[] = new Array(items.length) as R[];
  let cursor = 0;
  const consume = async (): Promise<void> => {
    while (true) {
      const i = cursor++;
      if (i >= items.length) return;
      results[i] = await worker(items[i]!, i);
    }
  };
  await Promise.all(
    Array.from({ length: Math.min(concurrency, items.length) }, () => consume()),
  );
  return results;
}

// ── Main ────────────────────────────────────────────────────────────────

async function loadJsonOrEmpty<T>(path: string): Promise<Record<string, T>> {
  try {
    return JSON.parse(await readFile(path, "utf-8")) as Record<string, T>;
  } catch (e) {
    if ((e as NodeJS.ErrnoException).code === "ENOENT") return {};
    throw e;
  }
}

async function writeJson(path: string, data: unknown): Promise<void> {
  await mkdir(join(path, ".."), { recursive: true });
  await writeFile(path, JSON.stringify(data, null, 2));
}

async function main() {
  const opts = parseArgs(process.argv.slice(2));
  await mkdir(CACHE_DIR, { recursive: true });
  await mkdir(OUT_DIR, { recursive: true });

  if (opts.resetPages && existsSync(PAGE_CACHE)) await unlink(PAGE_CACHE);
  if (opts.resetEnrichment && existsSync(ENRICH_CACHE)) await unlink(ENRICH_CACHE);

  const urls = collectUrls();
  console.log(`Source: ${urls.length} unique URLs across resources.ts`);

  const pageCache = await loadJsonOrEmpty<PageContent | PageFailure>(PAGE_CACHE);
  const enrichCache = await loadJsonOrEmpty<EnrichedResource | EnrichmentFailure>(
    ENRICH_CACHE,
  );

  const pageHits = urls.filter((u) => {
    const c = pageCache[urlId(u)];
    return c && !("error" in c);
  }).length;
  const enrichHits = urls.filter((u) => {
    const c = enrichCache[urlId(u)];
    return c && !("error" in c);
  }).length;
  console.log(
    `Cache: ${pageHits}/${urls.length} pages, ${enrichHits}/${urls.length} enrichments`,
  );

  // --only / --only-file: explicit URL allowlist. Bypasses cached-success
  // filter so it can re-process anything. Warn on URLs not present in
  // resources.ts so a typo isn't silent.
  if (opts.onlyUrlsFile) {
    const fromFile = (await readFile(opts.onlyUrlsFile, "utf-8"))
      .split("\n")
      .map((s) => s.trim())
      .filter((s) => s && !s.startsWith("#"));
    opts.onlyUrls = new Set([...(opts.onlyUrls ?? []), ...fromFile]);
  }

  let candidates: string[];
  if (opts.onlyUrls && opts.onlyUrls.size > 0) {
    const sourceSet = new Set(urls);
    const missing = [...opts.onlyUrls].filter((u) => !sourceSet.has(u));
    if (missing.length) {
      console.warn(`Warning: ${missing.length} --only URL(s) not in resources.ts:`);
      for (const u of missing) console.warn(`  ${u}`);
    }
    candidates = urls.filter((u) => opts.onlyUrls!.has(u));
    console.log(`--only: targeting ${candidates.length} URL(s)`);
  } else {
    candidates = urls.filter((u) => {
      const e = enrichCache[urlId(u)];
      return !e || "error" in e;
    });
  }

  const limited = opts.limit ? candidates.slice(0, opts.limit) : candidates;
  console.log(
    `Will process ${limited.length} URL${limited.length === 1 ? "" : "s"} ` +
      `(concurrency=${opts.concurrency}${opts.dryRun ? ", DRY RUN" : ""})`,
  );

  if (opts.dryRun) {
    for (const u of limited.slice(0, 20)) console.log(`  → ${u}`);
    if (limited.length > 20) console.log(`  … and ${limited.length - 20} more`);
    return;
  }

  const startedAt = Date.now();
  let done = 0;
  let pageOk = 0;
  let pageDegraded = 0;
  let pageFail = 0;
  let enrichOk = 0;
  let enrichFail = 0;
  let totalCost = 0;

  // Periodic flush every N completed items so a crash doesn't lose work.
  const flushEvery = 10;
  let dirtyPage = false;
  let dirtyEnrich = false;
  const flush = async () => {
    if (dirtyPage) {
      await writeJson(PAGE_CACHE, pageCache);
      dirtyPage = false;
    }
    if (dirtyEnrich) {
      await writeJson(ENRICH_CACHE, enrichCache);
      dirtyEnrich = false;
    }
  };

  await runWithConcurrency(limited, opts.concurrency, async (url) => {
    const id = urlId(url);

    // 1. Fetch page content (cached unless prior attempt was a failure).
    let page: PageContent | null = null;
    let fetchFailure: { reason: FetchFailureReason; message: string } | undefined;
    const cachedPage = pageCache[id];
    if (cachedPage && !("error" in cachedPage)) {
      page = cachedPage;
    } else {
      const result = await fetchWithRetry(url);
      if (result.ok) {
        pageCache[id] = result.page;
        page = result.page;
        if (result.page.degradationReason) pageDegraded++;
        else pageOk++;
      } else {
        pageCache[id] = {
          url,
          error: result.message,
          reason: result.reason,
          attemptedAt: new Date().toISOString(),
        };
        fetchFailure = { reason: result.reason, message: result.message };
        pageFail++;
      }
      dirtyPage = true;
    }

    // 2. Enrich with Claude — even on fetch failure, classify from URL alone.
    try {
      const env = await callClaude(buildPrompt(url, page, fetchFailure));
      if (env.is_error || !env.result) {
        throw new Error(`claude returned is_error or empty result`);
      }
      totalCost += env.total_cost_usd ?? 0;
      const fields = parseEnrichment(env.result);
      const enriched: EnrichedResource = {
        id,
        url,
        ...fields,
        enrichedAt: new Date().toISOString(),
      };
      enrichCache[id] = enriched;
      enrichOk++;
    } catch (e) {
      const err = e instanceof Error ? e.message : String(e);
      enrichCache[id] = {
        url,
        error: err,
        attemptedAt: new Date().toISOString(),
      };
      enrichFail++;
    }
    dirtyEnrich = true;

    done++;
    if (done % flushEvery === 0 || done === limited.length) {
      await flush();
      const elapsedSec = (Date.now() - startedAt) / 1000;
      const rate = done / elapsedSec;
      const etaSec = (limited.length - done) / rate;
      console.log(
        `  [${done}/${limited.length}] pages ok/degraded/fail: ${pageOk}/${pageDegraded}/${pageFail}, ` +
          `enrich ok/fail: ${enrichOk}/${enrichFail}, ` +
          `cost $${totalCost.toFixed(2)}, ` +
          `rate ${rate.toFixed(2)}/s, eta ${(etaSec / 60).toFixed(1)}min`,
      );
    }
  });

  await flush();

  // 3. Write the consolidated output. Only include successful enrichments.
  const enriched: EnrichedResource[] = [];
  for (const url of urls) {
    const e = enrichCache[urlId(url)];
    if (e && !("error" in e)) enriched.push(e);
  }
  enriched.sort((a, b) => a.title.localeCompare(b.title));
  await writeJson(OUT_FILE, enriched);

  console.log(`\nSummary`);
  console.log(`  Total URLs:               ${urls.length}`);
  console.log(`  Enriched (success):       ${enriched.length}`);
  console.log(`  Enrichment failures:      ${enrichFail}`);
  console.log(`  Page fetches ok:          ${pageOk}`);
  console.log(`  Page fetches degraded:    ${pageDegraded}  (bot wall / SPA shell — Claude classified from URL)`);
  console.log(`  Page fetch failures:      ${pageFail}`);
  console.log(`  Total Claude cost:        $${totalCost.toFixed(2)}`);
  console.log(`\nWrote: ${OUT_FILE}`);
  if (enrichFail > 0) {
    console.log(
      `\nRe-run to retry the ${enrichFail} failure(s) — they're in the cache but marked errored.`,
    );
  }
}

// Only run main when invoked directly (not when imported by a probe/test).
const invokedDirectly =
  import.meta.url === `file://${process.argv[1]}` ||
  import.meta.url.endsWith(process.argv[1] ?? "");
if (invokedDirectly) {
  main().catch((e) => {
    console.error("FATAL:", e);
    process.exit(1);
  });
}

export { fetchWithRetry, buildPrompt, detectBotWall, detectEmptyShell };
